/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LinksRouteImport } from './routes/links'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as CalendarYearRouteImport } from './routes/calendar.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarYearRoute = CalendarYearRouteImport.update({
  id: '/calendar/$year',
  path: '/calendar/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/contents': typeof ContentsRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/links': typeof LinksRoute
  '/strategy': typeof StrategyRoute
  '/calendar/$year': typeof CalendarYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/contents': typeof ContentsRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/links': typeof LinksRoute
  '/strategy': typeof StrategyRoute
  '/calendar/$year': typeof CalendarYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/contents': typeof ContentsRoute
  '/family': typeof FamilyRoute
  '/goals': typeof GoalsRoute
  '/links': typeof LinksRoute
  '/strategy': typeof StrategyRoute
  '/calendar/$year': typeof CalendarYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/contents'
    | '/family'
    | '/goals'
    | '/links'
    | '/strategy'
    | '/calendar/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/contents'
    | '/family'
    | '/goals'
    | '/links'
    | '/strategy'
    | '/calendar/$year'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/contents'
    | '/family'
    | '/goals'
    | '/links'
    | '/strategy'
    | '/calendar/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  ContentsRoute: typeof ContentsRoute
  FamilyRoute: typeof FamilyRoute
  GoalsRoute: typeof GoalsRoute
  LinksRoute: typeof LinksRoute
  StrategyRoute: typeof StrategyRoute
  CalendarYearRoute: typeof CalendarYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/$year': {
      id: '/calendar/$year'
      path: '/calendar/$year'
      fullPath: '/calendar/$year'
      preLoaderRoute: typeof CalendarYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  ContentsRoute: ContentsRoute,
  FamilyRoute: FamilyRoute,
  GoalsRoute: GoalsRoute,
  LinksRoute: LinksRoute,
  StrategyRoute: StrategyRoute,
  CalendarYearRoute: CalendarYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
